=== andrei-calin-dragomir/literature-study-pipeline/schemas/study_input_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "study_name": {
        "type": "string"
      },
      "research_goal": {
        "type": "string"
      },
      "research_questions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "inclusion_criteria": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "exclusion_criteria": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "year_min": {
        "type": "integer",
        "minimum": 0
      },
      "year_max": {
        "type": "integer",
        "minimum": 0
      },
      "search_word_groups": {
        "type": "array",
        "items": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "venue_rank_threshold": {
        "type": "string",
        "enum": ["A*", "A", "B", "C"]
      },
      "accepted_venue_types": {
        "type": "array",
        "items": {
          "type": "string",
          "enum": ["conf", "journals", "workshops", "informal", "phd", "books"]
        }
      },
      "manually_accepted_venue_codes" : {
        "type": "array",
        "items": {
          "type": "string"
        } 
      }
    },
    "required": [
      "search_word_groups",
      "inclusion_criteria",
      "exclusion_criteria",
      "year_min",
      "year_max"
    ]
}

=== andrei-calin-dragomir/literature-study-pipeline/study_input.json
{
    "study_name": "Green Computing in Distributed Systems: An analysis of Power-Efficient Container Orchestration Methods",
    "research_goal": "Characterize existing methods of performance-aware and energy efficient container orchestration of microservice based systems from the perspective of software engineering researchers and developers.",
    "research_questions": [
        "Which methods exist for orchestrating containerized applications with a focus on performance and/or energy efficiency optimization?",
        "Which type of orchestration policies results from the method and at what abstraction layer are they operating (machine level/ network level/ software level?",
        "Which type of resources are considered in the generation of the policies? (Overall CPU Utilization, Power consumption, Network throughput of the machines within a cluster.",
        "What are the limitations of existing methods?",
        "What are the benefits of these methods on resource utilization?"
    ],
    "inclusion_criteria": [
        "Study is written in English",
        "Must contain methods that orchestrate containers",
        "The method(s) used must take into account measurements and/or predictions",
        "Study contains an empirical evaluation of the policies presented"
    ],
    "exclusion_criteria": [
        "Methods presented are orchestrating VMs or containers deployed within VMs",
        "The method does not produce policies that optimize performance resource-wise"
    ],
    "year_min": 2019,
    "year_max": 2024,
    "search_word_groups": [
        ["microservice", "service", "container", "distributed", "kubernetes", "docker"],
        ["cluster", "orchestrat", "migrat", "scal", "load", "balanc"],
        ["method", "approach", "model", "algorithm"],
        ["performance", "energy", "resource"]
    ],
    "venue_rank_threshold" : "B",
    "accepted_venue_types": [
        "conf",
        "journals",
        "workshops"
    ],
    "manually_accepted_venue_codes" : [
        "conf/kbse", 
        "conf/wcre", 
        "conf/pemwn", 
        "conf/seke", 
        "conf/srds", 
        "conf/ccgrid", 
        "journals/tse", 
        "conf/supercomputer", 
        "journals/concurrency", 
        "journals/cluster", 
        "conf/socrob", 
        "conf/codesisss", 
        "conf/ast", 
        "conf/hipc", 
        "conf/ipccc", 
        "conf/cisis-spain", 
        "conf/cloudcom", 
        "conf/compsac", 
        "conf/sqm", 
        "conf/issre", 
        "conf/qrs", 
        "conf/msr", 
        "conf/opodis", 
        "journals/tpds", 
        "conf/adaEurope", 
        "journals/sosym", 
        "conf/sle", 
        "conf/hpdc", 
        "conf/icpads", 
        "conf/icgse", 
        "conf/sigsoft", 
        "journals/jpdc", 
        "conf/dcoss", 
        "conf/icdcs", 
        "conf/pts", 
        "conf/hoti", 
        "journals/ese", 
        "conf/icin", 
        "conf/spice", 
        "conf/sss", 
        "conf/ecsa", 
        "conf/fase", 
        "conf/ieeehpsc", 
        "conf/ispw", 
        "conf/modelsward", 
        "conf/ease", 
        "conf/apsec", 
        "conf/euromicro", 
        "journals/tosem", 
        "conf/seams", 
        "conf/scopes",
        "conf/vissoft",
        "journals/infsof",
        "conf/icse",
        "journals/tsc",
        "conf/emsoft",
        "conf/wosp",
        "conf/cnhpca",
        "journals/software",
        "conf/icsm",
        "journals/tjs",
        "conf/profes",
        "conf/sefm",
        "journals/iotj",
        "journals/smr",
        "conf/icsea",
        "conf/refsq",
        "conf/hpsr",
        "conf/icst2",
        "conf/xpu",
        "conf/somet",
        "journals/fgcs",
        "journals/ojiot",
        "conf/issta",
        "conf/uist",
        "conf/ucc",
        "conf/snpd",
        "journals/tcc",
        "conf/IEEEscc",
        "conf/setta",
        "conf/sbac-pad",
        "conf/splc",
        "conf/esem",
        "conf/hpcc",
        "conf/dais",
        "conf/tase",
        "conf/IEEEcloud",
        "journals/jsa",
        "conf/vrst",
        "journals/sqj",
        "conf/sera",
        "conf/gpc",
        "conf/sew",
        "conf/hpcasia",
        "conf/ssbse",
        "conf/closer",
        "conf/enase",
        "conf/icsa",
        "conf/ispass",
        "journals/ijcac"
    ]
}
